optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2025
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: dccf_crv
  # general parameters here
  embedding_size: 128
  intent_num: 128
  keep_rate: 0.98

  # data-specific parameters here
  layer_num: 2
  reg_weight: 1.0e-4
  cl_weight: 1.0e-3
  cl_temperature: 0.1
  kd_weight: 1.0e-2
  kd_temperature: 0.5
  sem_graph_topk: 10

  # for amazon
  amazon:
    layer_num: 2
    reg_weight: 1.0e-4
    cl_weight: 1.0e-3
    cl_temperature: 0.1
    kd_weight: 1.0e-2
    kd_temperature: 0.1
    contrastive_weight: 1.0e-4
    contrast_temp: 0.3
    gat_heads: 1
    sem_graph_topk: 10
  # for yelp
  yelp:
    layer_num: 2
    reg_weight: 1.0e-4
    cl_weight: 1.0e-4
    cl_temperature: 0.1
    kd_weight: 1.0e-3
    kd_temperature: 0.1
    contrastive_weight: 1.0e-30
    contrast_temp: 0.3
    gat_heads: 1
    sem_graph_topk: 10
  # for steam
  steam:
    layer_num: 1
    reg_weight: 1.0e-4
    cl_weight: 1.0e-3
    cl_temperature: 0.1
    kd_weight: 1.0e-2
    kd_temperature: 0.1
    contrastive_weight: 1.0e-30
    contrast_temp: 0.4
    gat_heads: 1
    sem_graph_topk: 10

