optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2025
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: gccf_eg_crv
  # general parameters here
  keep_rate: 0.8
  embedding_size: 128

  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-4
  contrastive_weight: 0.1
  contrast_temp: 0.4
  kd_weight: 1.0e-2
  kd_temperature: 0.2
  gat_heads: 1
  sem_graph_topk: 10
  llm_model: gpt-4o
  api_key: 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
  api_batch_size: 1
  api_calls_per_node: 1
  preprocess_gate_labels: False

  # for amazon
  amazon:
    layer_num: 3
    keep_rate: 0.98
    contrastive_weight: 1.0e-3
    contrast_temp: 0.4
    reg_weight: 1.0e-6
    kd_weight: 1.0e-3
    kd_temperature: 0.1
    gat_heads: 1
    sem_graph_topk: 10
    gate_supervision_weight: 1.0e-1

  # for yelp
  yelp:
    layer_num: 3
    keep_rate: 0.8
    contrastive_weight: 5.0e-3
    contrast_temp: 0.3
    reg_weight: 1.0e-6
    kd_weight: 2.0
    kd_temperature: 0.1
    gat_heads: 1
    sem_graph_topk: 5
    gate_supervision_weight: 8.0e-1

  # for steam:
  steam:
    layer_num: 3
    keep_rate: 0.98
    contrastive_weight: 5.0e-3
    contrast_temp: 0.4
    reg_weight: 1.0e-6
    kd_weight: 3.0e-1
    kd_temperature: 0.1
    gat_heads: 1
    sem_graph_topk: 10
    gate_supervision_weight: 1.0e-2
