optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  log_loss: false
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 5
  trainer: autocf_trainer

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: autocf_eg_crv
  # general parameters here
  embedding_size: 64
  keep_rate: 0.2
  gt_layer: 1
  head_num: 4
  seed_num: 100
  mask_depth: 2
  fix_steps: 10

  # data-specific parameters here
  gcn_layer: 2
  reg_weight: 1.0e-6
  ssl_reg: 1
  kd_weight: 1.0e-2
  kd_temperature: 0.5
  sem_graph_topk: 10
  llm_model: gpt-4o
  api_key: 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
  api_batch_size: 1
  api_calls_per_node: 1
  preprocess_gate_labels: False

  # for amazon
  amazon:
    layer_num: 3
    gcn_layer: 2
    reg_weight: 1.0e-6
    ssl_reg: 1
    kd_weight: 1.0e-1
    kd_temperature: 0.5
    contrastive_weight: 1.0e-30
    contrast_temp: 0.3
    gat_heads: 1
    sem_graph_topk: 10
    gate_supervision_weight: 1.0

  # for yelp
  yelp:
    layer_num: 3
    gcn_layer: 2
    reg_weight: 5.0e-8
    ssl_reg: 1
    kd_weight: 1.0e-2
    kd_temperature: 0.2
    contrastive_weight: 1.0e-30
    contrast_temp: 0.3
    gat_heads: 1
    sem_graph_topk: 10
    gate_supervision_weight: 1.0

  # for steam
  steam:
    layer_num: 3
    gcn_layer: 2
    reg_weight: 5.0e-8
    ssl_reg: 4.0e-1
    kd_weight: 5.0e-3
    kd_temperature: 0.2
    contrastive_weight: 1.0e-30
    contrast_temp: 0.3
    gat_heads: 1
    sem_graph_topk: 10
    gate_supervision_weight: 1.0e+1
